name: 'GitHub Actions Report Bot'

on:
  push:
    branches: [ master ]
  watch:
    types: started

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Run script
<<<<<<< HEAD
        run: python3 setup.py
=======
        run: python3 setup.py
>>>>>>> origin/master
